### ISSUE TITLE
Time on frontend differs from backend input

### ISSUE THREAD

**Issue by andreasdueren** [nathanlesage/oc-campaignr#4]
running on build 464 with latest version of campaignr. 
octoberCMS is set to UTC and I'm currently in UTC+1

**Comment by nathanlesage** [comment]
You mentioned two hours on the forum, right? I'll have a look into this, but can't promise I'll find the culprit -- the dates are saved as `Y-m-d H:i:s` in the database, that is: without timezone information. Maybe I can somehow set the Carbon class to use the backend timezone instead of server time (if that's the case), I'll have a look at this!

**Comment by nathanlesage** [comment]
Closing in preparation to archiving this repository.
